### ISSUE TITLE
DESIGNED FOR THE FUTURE

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [maximbalyk/template#44]
<img width="1171" alt="Знімок екрана 2023-04-19 о 16 44 04" src="https://user-images.githubusercontent.com/59687966/233112060-1555cbee-9df4-45cb-bf50-9743a142b2c7.png">

Не звертав раніше уваги, з текстом так і було задумано?

**Comment by maximbalyk** [comment]
Так там в дизайні текст залазить на картинку на дві літери.
