### ISSUE TITLE
detectKeyDown

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [maximbalyk/template#45]
`detectKeyDown` в біографіі працює лише один раз тому що він не вказаний в залежностях в `useEffect`
```
 useEffect(() => {
    document.addEventListener("keydown", detectKeyDown, true);
    return () => {
        document.removeEventListener("keydown", detectKeyDown, true);
    };
}, []);
```

**Comment by DmitriiMelnikOnix** [comment]
Майже такий же приклад як робирали на занятті 😄

**Comment by maximbalyk** [comment]
блін, це я його поломав коли прикручував щось інше. і забув про нього. дякую що нагадав!)
